### ISSUE TITLE
platform - write for us

### ISSUE THREAD

**Issue by sri-rang** [modulepattern/somewhatpassive#37]
- [ ] allow prospective authors to write for us
- [ ] enable across the network
- [ ] workflow / process / attributions and reward
