### ISSUE TITLE
rust - launch

### ISSUE THREAD

**Issue by sri-rang** [modulepattern/somewhatpassive#8]
- [x] setup web app
- [x] first featured post
- [x] mailing list setup
- [x] google analytics setup
- [x] buy domain
- [x] deploy
